FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY ./static ./static
COPY ./templates ./templates
COPY ./app.py ./app.py

EXPOSE 5000/tcp

CMD [ "python","app.py" ]
